(function(){'use strict';
const URL='https://hossnadharma.substack.com';
const KEY='hossna_newsletter_dismissed_at';
const modal=document.createElement('div');
modal.className='newsletter-modal';modal.setAttribute('aria-hidden','true');
modal.innerHTML=`<div class="newsletter-modal__backdrop" data-newsletter-close></div><section class="newsletter-modal__dialog" role="dialog" aria-modal="true" aria-labelledby="newsletter-title"><button class="newsletter-modal__close" type="button" aria-label="Fermer" data-newsletter-close>×</button><div class="newsletter-modal__visual" aria-hidden="true"><span class="newsletter-modal__script">La lettre de Housna</span><div class="newsletter-modal__orb newsletter-modal__orb--1"></div><div class="newsletter-modal__orb newsletter-modal__orb--2"></div><div class="newsletter-modal__mark">H</div></div><div class="newsletter-modal__content"><span class="mono-cap">La newsletter hossnadharma</span><h2 id="newsletter-title">Et si votre boîte mail devenait aussi un endroit où <em>ralentir ?</em></h2><p>Des lettres autour du corps, de l’intimité, de la santé et de la vie concrète.</p><p class="newsletter-modal__promise">Pas de mails pour remplir votre boîte. J’écris quand il y a quelque chose à partager.</p><a class="btn btn--clay btn--lg newsletter-submit" href="${URL}" target="_blank" rel="noopener">Recevoir les lettres →</a></div></section>`;
document.body.appendChild(modal);
const inline=document.createElement('section');inline.className='newsletter-inline';inline.innerHTML=`<div class="container"><div class="newsletter-inline__panel reveal"><div><span class="mono-cap mono-cap--light">La lettre hossnadharma</span><h2>Des mots à garder près de soi.</h2><p>Corps, intimité, santé et vie concrète, dans votre boîte mail.</p></div><a class="btn newsletter-open-btn" href="${URL}" target="_blank" rel="noopener">Recevoir la lettre →</a></div></div>`;const footer=document.querySelector('.footer');if(footer)footer.parentNode.insertBefore(inline,footer);
function open(){modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('newsletter-lock')}
function close(){modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('newsletter-lock');localStorage.setItem(KEY,String(Date.now()))}
document.addEventListener('click',e=>{if(e.target.closest('[data-newsletter-close]'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
const last=Number(localStorage.getItem(KEY)||0);if(!last||Date.now()-last>10*86400000){let fired=false;const trigger=()=>{if(fired)return;fired=true;open();window.removeEventListener('scroll',onScroll)};const onScroll=()=>{const h=document.documentElement.scrollHeight-window.innerHeight;if(h>0&&window.scrollY/h>.42)trigger()};window.addEventListener('scroll',onScroll,{passive:true});setTimeout(trigger,9000)}
})();